{
	"version": 1616524264,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/hero-sheet0.png",
		"images/hero-sheet1.png",
		"images/hero-sheet2.png",
		"images/hero-sheet3.png",
		"images/hero-sheet4.png",
		"images/oct-sheet0.png",
		"images/oct-sheet1.png",
		"images/start-sheet0.png",
		"images/correcct-sheet0.png",
		"images/correcct-sheet1.png",
		"images/correcct-sheet2.png",
		"images/sprite-sheet0.png",
		"images/floor1-sheet0.png",
		"images/tarn-sheet0.png",
		"images/covit-sheet0.png",
		"images/covit-sheet1.png",
		"images/fal-sheet0.png",
		"images/fal-sheet1.png",
		"images/login-sheet0.png",
		"images/oct2-sheet0.png",
		"images/oct2-sheet1.png",
		"images/sprite2-sheet0.png",
		"images/start1-sheet0.png",
		"images/about-sheet0.png",
		"images/howto-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/login1-sheet0.png",
		"images/warn-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/jot-sheet0.png",
		"images/jot-sheet1.png",
		"images/sprite6-sheet0.png",
		"images/23783converted-sheet0.png",
		"images/vectorsmartobject-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite7-sheet1.png",
		"images/about2-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"media/10 mouse click sound effects - 10 effects (1) (1).m4a",
		"media/10 mouse click sound effects - 10 effects (1) (1).ogg",
		"media/game of thrones - sound of westeros.m4a",
		"media/game of thrones - sound of westeros.ogg",
		"media/imagine dragons warriors instrumental thing.m4a",
		"media/imagine dragons warriors instrumental thing.ogg",
		"media/queen - we are the champions (chorus only).m4a",
		"media/queen - we are the champions (chorus only).ogg",
		"media/ดาวนโหลด เสยงคลก, click (เสยงคลกเมาส).m4a",
		"media/ดาวนโหลด เสยงคลก, click (เสยงคลกเมาส).ogg",
		"media/เสยง effect ผด.m4a",
		"media/เสยง effect ผด.ogg",
		"media/เสยงปรบมอ sound effect.m4a",
		"media/เสยงปรบมอ sound effect.ogg",
		"media/เอฟเฟค เสยง ตอย.m4a",
		"media/เอฟเฟค เสยง ตอย.ogg",
		"media/แจกเสยงดาบหลายรปแบบ พรอมวธโหลด (1).m4a",
		"media/แจกเสยงดาบหลายรปแบบ พรอมวธโหลด (1).ogg",
		"media/click.m4a",
		"media/click.ogg",
		"media/death-sound-effect.m4a",
		"media/death-sound-effect.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"25640323-220930-844.webm"
	]
}